version: '3.7'

services:
  rabbitmq:
    container_name: rabbitmqserver
    image: rabbitmq:3.7-management-alpine
    restart: on-failure
    networks:
      testing_net:
        ipv4_address: 172.18.0.2
    ports:
      - '15672:15672'
      - '5672:5672'

  mqsetup:
    container_name: mq
    image: mq
    restart: on-failure
    depends_on:
      - rabbitmq
    networks:
      testing_net:
        ipv4_address: 172.18.0.3

  loadbalancer:
    container_name: loadbalancer
    image: loadbalancer
    restart: on-failure
    depends_on:
      - rabbitmq
    networks:
      testing_net:
        ipv4_address: 172.18.50.50
    ports:
      - '8080:8080'

  server1:
    container_name: server1
    image: server
    restart: on-failure
    depends_on:
      - rabbitmq
    networks:
      testing_net:
        ipv4_address: 172.18.1.1
    ports:
      - '8081:8081'


  server2:
    container_name: server2
    image: server
    restart: on-failure
    depends_on:
      - rabbitmq
    networks:
      testing_net:
        ipv4_address: 172.18.1.2
    ports:
      - '8082:8081'

  server3:
    container_name: server3
    image: server
    restart: on-failure
    depends_on:
      - rabbitmq
    networks:
      testing_net:
        ipv4_address: 172.18.1.3
    ports:
      - '8083:8081'

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16